version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/external-data-integration # directory where steps will run
    docker: # run the steps with Docker
      - image: angieslist/circleci-sbt:8-jdk # ...with this image as the primary container; this is where all `steps` will run
        auth: 
          username: $DOCKER_USERNAME
          password: $DOCKER_AUTH
    steps: # a collection of executable commands
      - checkout # check out source code to working directory
      # restore cache (if needed/available)
      - restore_cache:
          key: dep-cache-{{ checksum "pom.xml" }}
      - run: mvn clean package
      # populate the cache
      - save_cache:
          paths:
            - ~/target/repository
          key: dep-cache-{{ checksum "pom.xml" }}
      - run: mkdir artifacts ; cp target/*.jar artifacts/application.jar
      - run:
          name: publish to s3
          command: aws s3 cp artifacts/application.jar s3://${MULESOFT_CODE_BUCKET}/artifact/${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}/application.jar
workflows:
  version: 2
  build_test_publish:
    jobs:
      - build:
          context: mulesoft-publish